<?php

namespace AppBundle\Repository;

/**
 * AnimationTexteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimationTexteRepository extends \Doctrine\ORM\EntityRepository
{
}
