<?php

namespace AppBundle\Repository;

/**
 * GenreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenreRepository extends \Doctrine\ORM\EntityRepository
{
    
  public function getNbGenre() {
  
        return $this->createQueryBuilder('g')
  
                        ->select('COUNT(g)')
                        
                
                        ->getQuery()
  
                        ->getSingleScalarResult();
  
    }

    
}
