<?php

namespace AppBundle\Repository;

/**
 * HeaderTexteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeaderTexteRepository extends \Doctrine\ORM\EntityRepository
{
}
