<?php

namespace AppBundle\Repository;

/**
 * ImageMobileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageMobileRepository extends \Doctrine\ORM\EntityRepository
{
}
