<?php

namespace AppBundle\Repository;

/**
 * PresentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PresentRepository extends \Doctrine\ORM\EntityRepository
{
}
