<?php

namespace AppBundle\Repository;

/**
 * ProductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductionRepository extends \Doctrine\ORM\EntityRepository
{
         public function getNbPublishProd() {
      
        $qb = $this->createQueryBuilder('pr');
  

        $qb
                        ->select('COUNT(pr)')
                        ->where('pr.publier = 1');
                        
                        return $qb
                        ->getQuery()
                        ->getSingleScalarResult();
  
    } 
    
}
