<?php

namespace AppBundle\Repository;

/**
 * SectionRowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionRowRepository extends \Doctrine\ORM\EntityRepository
{
}
