<?php

namespace AppBundle\Repository;

/**
 * SectionNameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionNameRepository extends \Doctrine\ORM\EntityRepository
{
}
